#spring.application.name=employee-management-service
server:
  port: 8080

spring:

  data:
    mongodb:
      url: mongodb://localhost:27017/employeedb


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example: DEBUG
